<?php
require __DIR__ . '/config.php'; require __DIR__ . '/db.php'; $db=db();
$activities=$db->query("SELECT * FROM activities ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);
$resorts=$db->query("SELECT * FROM resorts ORDER BY id ASC")->fetchAll(PDO::FETCH_ASSOC);
function base_url(){global $BASE_URL; if($BASE_URL) return rtrim($BASE_URL,'/'); $s=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http'; return $s."://".$_SERVER['HTTP_HOST'];}
?>
<!doctype html><html lang='en'><head><meta charset='utf-8'><title><?=clean($SITE_NAME)?> – Nature & Adventure in Dandeli</title><meta name='viewport' content='width=device-width, initial-scale=1'><meta name='description' content='Book river rafting, jungle safari, kayaking and stays in Dandeli, Karnataka. Direct bookings, local support.'><link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet'><link rel='stylesheet' href='assets/style.css'>
<script type='application/ld+json'>{"@context":"https://schema.org","@type":"TravelAgency","name":"<?=clean($SITE_NAME)?>","url":"<?=clean(base_url())?>","areaServed":"Dandeli, Karnataka, India","sameAs":[],"priceRange":"₹₹","description":"Adventure activities and resort stays in Dandeli: rafting, jungle safari, kayaking, and more."}</script>
</head><body>
<nav class='navbar navbar-expand-lg border-bottom'><div class='container'><a class='navbar-brand fw-bold' href='index.php'><img src='assets/logo.png' style='height:36px;vertical-align:-6px'> <?=clean($SITE_NAME)?></a><button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#nav'><span class='navbar-toggler-icon'></span></button><div id='nav' class='collapse navbar-collapse'><ul class='navbar-nav ms-auto'><li class='nav-item'><a href='#activities' class='nav-link'>Activities</a></li><li class='nav-item'><a href='#stays' class='nav-link'>Resorts</a></li><li class='nav-item'><a href='booking.php' class='btn btn-brand ms-lg-3'>Book Now</a></li><li class='nav-item'><a href='contact.php' class='nav-link'>Contact</a></li></ul></div></div></nav>
<header class='hero text-center d-flex align-items-center'><div class='container inner'><h1 class='display-5 fw-bold'>Dandeli: Nature & Adventure at its Best</h1><p class='lead'>White‑water rafting, jungle safaris, kayaking, treks & cozy stays by the Kali River.</p><a class='btn btn-brand btn-lg me-2' href='booking.php'>Get Instant Quote</a><a class='btn btn-outline-light btn-lg' href='#activities'>Explore Activities</a></div></header>
<section id='activities' class='py-5'><div class='container'><h2 class='section-title mb-3'>Top Activities</h2><div class='row g-4'><?php foreach($activities as $a):?><div class='col-md-4'><div class='card h-100 shadow-sm'><img src='https://source.unsplash.com/600x400/?rafting,river' class='card-img-top'><div class='card-body'><h5 class='card-title'><?=clean($a['name'])?></h5><p class='card-text'><?=clean($a['short_desc'])?></p><p class='fw-semibold'>From ₹ <?=number_format($a['price'])?> / person</p><a href='booking.php?type=activity&id=<?=$a['id']?>' class='btn btn-brand'>Book</a></div></div></div><?php endforeach;?></div></div></section>
<section id='stays' class='py-5 bg-light'><div class='container'><h2 class='section-title mb-3'>Resorts & Camps</h2><div class='row g-4'><?php foreach($resorts as $r):?><div class='col-md-4'><div class='card h-100 shadow-sm'><img src='https://source.unsplash.com/600x400/?resort,forest' class='card-img-top'><div class='card-body'><h5 class='card-title'><?=clean($r['name'])?></h5><p class='card-text'><?=clean($r['short_desc'])?></p><p class='fw-semibold'>From ₹ <?=number_format($r['price'])?> / night</p><a href='booking.php?type=resort&id=<?=$r['id']?>' class='btn btn-brand'>Book</a></div></div></div><?php endforeach;?></div></div></section>
<section class='py-5'><div class='container'><h2 class='section-title mb-3'>How to Reach</h2><p>By air: Hubballi (HBX) is the nearest airport, then ~2.5–3.5 hours by road to Dandeli. By train: Alnavar/Londa Junctions are common rail heads, then local taxis. By road: Good connectivity from Goa, Belagavi, Hubballi, Karwar.</p></div></section>
<footer class='py-4'><div class='container d-flex flex-column flex-md-row justify-content-between'><div>&copy; <?=date('Y')?> <?=clean($SITE_NAME)?>. All rights reserved.</div><div><a href='admin.php' class='link-light'>Admin</a> | <a href='sitemap.xml' class='link-light'>Sitemap</a></div></div></footer>
<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js'></script></body></html>